//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNhom1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Region()
        {
            this.Trees = new HashSet<Tree>();
            this.ImgRe = "~/image/background.jpg";
        }
    
        public int Id { get; set; }
        [NotMapped]
        public List<Region> ListRe { get; set; }
        public string IDRe { get; set; }
        public string NameRe { get; set; }
        public string ImgRe { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tree> Trees { get; set; }
    }
}
