//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNhom1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Tree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tree()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ImageTree = "~/image/background.jpg";
        }
    
        public int TreeID { get; set; }
        public string NameTree { get; set; }
        public string DecriptionTree { get; set; }
        public string IDRe { get; set; }
        public decimal Price { get; set; }
        public string ImageTree { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Region Region { get; set; }
    }
}
